### ISSUE TITLE
Cannot build on RHEL 6

### ISSUE THREAD

**Issue by kuntzagk** [UtrechtUniversity/davrods#11]
Build fails on RHEL6. I think I have all required packages installed.
Where are AUTHN_PROVIDER_VERSION and AP_AUTH_INTERNAL_PER_CONF supposed to come from?

```
[root@icat build]# make
[ 12%] Building C object CMakeFiles/mod_davrods.dir/auth.c.o
/root/davrods-4.2.1_1.3.0/auth.c: In function ‘davrods_auth_register’:
/root/davrods-4.2.1_1.3.0/auth.c:442: warning: implicit declaration of function ‘ap_register_auth_provider’
/root/davrods-4.2.1_1.3.0/auth.c:445: error: ‘AUTHN_PROVIDER_VERSION’ undeclared (first use in this function)
/root/davrods-4.2.1_1.3.0/auth.c:445: error: (Each undeclared identifier is reported only once
/root/davrods-4.2.1_1.3.0/auth.c:445: error: for each function it appears in.)
/root/davrods-4.2.1_1.3.0/auth.c:447: error: ‘AP_AUTH_INTERNAL_PER_CONF’ undeclared (first use in this function)
make[2]: *** [CMakeFiles/mod_davrods.dir/auth.c.o] Error 1
make[1]: *** [CMakeFiles/mod_davrods.dir/all] Error 2
make: *** [all] Error 2

```

**Comment by cjsmeele** [comment]
RHEL6 ships with Apache 2.2, while Davrods requires Apache 2.4 or newer.
The build errors you are seeing are caused by additions to the API for registering authentication handlers, which we depend on.

We develop and test Davrods for CentOS7 / RHEL7.
Although we do not support RHEL6, if you must use this RHEL version then you might be able to get Davrods to work if you [get Apache 2.4 to run on it](https://developers.redhat.com/blog/2014/10/01/using-apache-httpd-2-4-rhel6/), though this is not something that we have tested.
