### ISSUE TITLE
Compute checksums on upload?

### ISSUE THREAD

**Issue by holtgrewe** [UtrechtUniversity/davrods#30]
davrods is an incredibly useful software package, again: thanks for it.

It would be great if davrods would compute checksums for uploaded files. Is this possible?

**Comment by tsmeele** [comment]
Hi Manuel,

iRODS server side checksums can be implemented using an iRODS dynamic policy rule on iRODS API calls used by davrods.  You might want to implement such operation asynchronously (e.g. delay rule or background process) so that users do not experience performance degradation on their WebDAV calls when this is done for larger files.

Checksums at client side would require a WebDAV client to do such locally. Unfortjnately, as far as we know, the WebDAV protocol does not include a standardized way to communicate a client side checksum to the WebDAV server,
otherwise indeed we might be able to assert correct receipt of the data.

Cheers,

Ton


On Tue, 2023-05-02 at 02:39 -0700, Manuel Holtgrewe wrote:

davrods is an incredibly useful software package, again: thanks for it.

It would be great if davrods would compute checksums for uploaded files. Is this possible?

**Comment by holtgrewe** [comment]
Dear Ton,

thank you for your reply. I guess a delay rule would be most appropriate. We upload .md5 files or manifest checksum files with out data anyway to circumvent "the right checksum from incomplete data" issue.

We'll look further into the rules then.

Best wishes,
Manuel
